name: Deploy React App
on: push
jobs:
  # test_app: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get repository code
  #       uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Test application
  #       run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build application
        run: npm run build
      - name: Deploy
        run: echo Deploying
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: lint application
        run: npm run eslint